version: '3.8'

services:
  mysql:
    image: mysql:8.0  # Alterando para a versão disponível
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: esp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ruby-script:
    build:
      context: ./ruby-script
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: esp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

volumes:
  mysql_data:
