version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_python
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: esp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python-script:
    build:
      context: ./python-script
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: esp_data
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

volumes:
  mysql_data:


