version: '3.8'

services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
      MYSQL_USER: tester
      MYSQL_PASSWORD: secret
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
    environment:
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - db
